export const COCKTAILS_FETCH_START = "COCKTAILS_FETCH_START";

export const NEW_COCKTAIL_POST_START = "NEW_COCKTAIL_POST_START";

export const COCKTAIL_DELETE_START = "COCKTAIL_DELETE_START";

export const COCKTAIL_EDIT_START = "COCKTAIL_EDIT_START";
